export const paths = {
    LOGIN: "/login",
    FORGET_PASSWORD: "/forget-password",
    VERIFY_OTP: "/verify-otp",
    RESET_PASSWORD: "/reset-password",
    HOME: "/home",
    DASHBOARD: "/dashboard",
    SALES: "/sales",
    CUSTOMER_LIST: '/customer',
    CUSTOMER_CREATE: '/customer/create',
    RESELLER_LIST: '/reseller',
    RESELLER_CREATE: '/reseller/create',
    ADMIN_CREATE: '/admin/create',
    ADMIN_LIST: '/admin',
    PROFILE: "/profile",
    VISA_SERVICE_LIST: '/visa-services',
    VISA_SERVICE_CREATE: '/visa-services/create',
    SETTING: "/setting",
    CATEGORY: "/category",
    CATEGORY_SERVICE: "/category-service",
    ONBOARDING_SERVICE: "/onboarding-service",
    EMPLOYER: "/employer",
    DOWNLOAD: "download"
}